FROM ethereum/client-go:stable
COPY genesis-poa.json /blockchain/genesis-poa.json
RUN geth --ipcdisable --datadir /blockchain init /blockchain/genesis-poa.json
COPY static-nodes.json /blockchain/geth/static-nodes.json
COPY keystore/server-privatekey /blockchain/keystore/server-privatekey
RUN touch /blockchain/password.txt