version: "3.6"
services:
  api:
    image: web3labs/epirus-free-api:latest
    environment:
      - NODE_ENDPOINT=http://172.16.238.10:8880
      - MONGO_CLIENT_URI=mongodb://172.16.238.14:27017
      - REINDEX_ENDPOINT=http://ingestion/reindex/
      - MONGO_DB_NAME=epirus
    networks:
      - epirus

  web:
    image: web3labs/epirus-free-web:latest
    environment:
      - API_URL=/api
    depends_on:
      - api
    networks:
      - epirus
  
  ingestion:
    image: web3labs/epirus-free-ingestion:latest
    environment:
      - NODE_ENDPOINT=http://172.16.238.10:8880
      - MONGO_CLIENT_URI=mongodb://172.16.238.14:27017
      - MONGO_DB_NAME=epirus
    networks:
      - epirus
      
  nginx:
    image: nginx:latest
    volumes:
      - ./explorer/nginx.conf:/etc/nginx/nginx.conf
      - ./explorer/5xx.html:/www/error_pages/5xx.html
    ports:
      - 80:80
    depends_on:
      - api
      - web
    networks:
      - epirus

networks:
  epirus:
    external:
      name: svote_ethereum
